name: CI/CD Pipeline with Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build static site
        run: |
          mkdir build
          cp index.html build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-files
          path: build/

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/*"
          target: "/var/www/html/"
